# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FtthChecker
                                 A QGIS plugin
 Vérifie la topologie géométrique FTTH
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-06
        copyright            : (C) 2026 by Youssef
        email                : youssef.rabah@etudiant-fst.utm.tn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FtthChecker class from file FtthChecker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ftth_checker import FtthChecker
    return FtthChecker(iface)